### ISSUE TITLE
The newly added music is way too loud.

### ISSUE THREAD

**Issue by MegaWooloo** [Cold-War-Project/CWP-Main#100]
The new music in the game is too loud, and it sounds distorted.

**Comment by corg343** [comment]
This is a bug I've experienced in base game. Does it happen consistently?

**Comment by MegaWooloo** [comment]
It happens every time the music plays. Everything else sounds how it does normally, but the new music is considerably louder

**Comment by corg343** [comment]
I can't find anyone else experiencing this. Very strange.
