### ISSUE TITLE
Some buildings consume and produce their own output

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#114]
nuclear weapons facility both produces and consumes nuke facilities

**Comment by Matti-96** [comment]
looks like it is working as designed.

nuclear weapons facility production method produces nuclear warheads & nuclear weapons silo production method consumes nuclear warheads

as they are in the same building, it appears that the nuclear weapons facility both produces and consumes nuke facilities

if nuclear weapons get expanded, I would suggest splitting the building into 2 separate buildings: Nuclear Weapon Production Complex for producing & Nuclear Weapon Launching Facility for consuming
