### ISSUE TITLE
Unhandled Exception C0000005 (EXCEPTION_ACCESS_VIOLATION) at address 0x00007FF62A05C620

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#123]
it was 2008 and my game just crashed while i was fighting the french

**Comment by EdnaldoPereira520** [comment]
[exception.txt](https://github.com/Cold-War-Project/CWP-Main/files/11140210/exception.txt)
[debug.log](https://github.com/Cold-War-Project/CWP-Main/files/11140211/debug.log)
[error.log](https://github.com/Cold-War-Project/CWP-Main/files/11140212/error.log)
[game.log](https://github.com/Cold-War-Project/CWP-Main/files/11140213/game.log)
