### ISSUE TITLE
Missing loc for Cantonese

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#174]
Cantonese localization

**Comment by Mr-Jangoon** [comment]
we should find a localizer

**Comment by DZappala** [comment]
This is in regards to the missing loc for the cantonese culture in game.

**Comment by Mr-Jangoon** [comment]
> This is in regards to the missing loc for the cantonese culture in game.

what parts of the localization would happen to be missing currently?

**Comment by raxo2222** [comment]
Raw string I guess - as in raw_string_you_see instead of "Raw string you see"

**Comment by raxo2222** [comment]
"cantonese" was corrected to "Cantonese" :)
