### ISSUE TITLE
Missing fonts/text

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#25]
Game is missing fonts/text
Appears at the start
To repro, just launch the game

System details:
Fedora Linux 36 Silverblue
AMD Radeon 5600XT
Victoria 3 1.2.7, CWP 0.1.0 Alpha

**Comment by Vildravn** [comment]
![image](https://user-images.githubusercontent.com/1076814/229191847-f0f74b62-7326-46c1-8259-1c4332404b6f.png)

**Comment by Vildravn** [comment]
Deleting the mod's fonts folder works as a workaround
