### ISSUE TITLE
There are empty spaces in new buildings section of macrobuilder

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#27]
Missing buildings at bottom of  macrobuilder

**Comment by DZappala** [comment]
This has to do with the custom macro builder UI. Possibly just a `visible =` issue, possibly unfixable due to paradox not letting us use custom data models.

**Comment by Arcadyi** [comment]
visible = yes does not work *yet*, that might change when PDX decides to add that functionality to fixedgridboxes
