### ISSUE TITLE
UN & NATO Application list doesn't clear out annexed/destroyed applicants

### ISSUE THREAD

**Issue by Arcadyi** [Cold-War-Project/CWP-Main#324]
Was using
		clear_global_variable_list =  un_application_list
		clear_global_variable_list =  nato_application_list
but these have since become non-functional

**Comment by raxo2222** [comment]
Issue is that it doesn't exist:
Search "clear_global_variable_list = un_application_list" (0 hits in 0 files of 1576 searched)
