### ISSUE TITLE
is_target_in_global_variable_list name flag doesn't exist

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#354]
https://github.com/Cold-War-Project/CWP-Main/blob/725d8b219512c9ae4567acd40c950d56291b3686/common/script_values/ai_readiness_values.txt#L119

**Comment by DZappala** [comment]
Error log states this variable doesn't exist. This error is at game start and likely means we just need to check if it exists.

**Comment by raxo2222** [comment]
It was syntax error:
is_target_in_global_variable_list = {
					variable = warsaw_pact_application_list <---- INVALID
					name = warsaw_pact_application_list <---- Its always name = in is_target_in_global_variable_list 
					target = THIS
				}
