### ISSUE TITLE
Missing small IG icons

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#37]
Missing small icons for IGs - I think only vanilla ones show up on highest  legitimacy suggestions buttons

**Comment by DZappala** [comment]
![image](https://user-images.githubusercontent.com/40328432/229199054-437dc48b-22c7-4284-bb2b-3b22315c8ca8.png)

**Comment by raxo2222** [comment]
Fixed it - someone forgot to update text icons with mod IGs
