### ISSUE TITLE
Massive coalitions

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#449]
Massive party coalitions still coaless into one party despite culling that was done to party size. a new party algorithm should be implemented. 

blockers: Unsure as to what order party support is calculated in, so it seems like this is rhe main catalyst for huge party coalitions. 

Possible fixes: 
- adding more variables to party formation to make it more diversified. 
- scaling all numbers to increments of 1s rather than 10s 
- increasing the rate if logarithmic falloff
- putting caps on max party join points
- setting the base value to some negative number. vanilla starts it at -5
- putting some restrictions on which igs can join which parties. only minor ones however.

**Comment by JackEPepper** [comment]
I slapped a quick and dirty fix on my fixes branch, just set join value to zero above 4 members
