### ISSUE TITLE
bad nato/warsaw pact applicant country scope

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#461]
There are following errors: [22:26:28][jomini_effect.cpp:319]: Event target 'nato_applicant_country_scope' is used but is never set. Setting it in an unused scripted trigger or effect does not count [22:26:28][jomini_effect.cpp:319]: Event target 'warsaw_pact_applicant_country_scope' is used but is never set. Setting it in an unused scripted trigger or effect does not count.
Its in CWP_events\warsaw_pact_events\warsaw_pact_ai_voting.txt
CWP_events\nato_events\nato_ai_voting

**Comment by raxo2222** [comment]
It appears thing was deleted by mistake while fixing bug.
https://github.com/Cold-War-Project/CWP-Main/commit/57a74be4790266bd591aeb89a56a5c568016b5fa
