### ISSUE TITLE
Government dividents are affected by gdp to debt ratio, leading to death spiral.

### ISSUE THREAD

**Issue by emelrad12** [Cold-War-Project/CWP-Main#469]
![image](https://github.com/Cold-War-Project/CWP-Main/assets/16389331/ab240e84-7bd3-4abb-82ec-6ce9a7522a86)

**Comment by raxo2222** [comment]
Drop save on here

**Comment by raxo2222** [comment]
So this is vanilla mechanic. Apparently PDX hate socialism and prefer communism - that is worker coops.
