### ISSUE TITLE
Nuclear Research JE missing

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#471]
As Japan in 1960, I have establish the Nuclear Research Facility through the journal decision and have researched Nuclear Reactors. However, the research JE is not popping up. This was done on the latest imf branch (commit 0001985 - ai more competent).

**Comment by PrimePhoenix9** [comment]
This is a save few months after establishing the Nuclear Research Facility.
[Japan 1960 Nuclear JE Missing.zip](https://github.com/Cold-War-Project/CWP-Main/files/12206942/Japan.1960.Nuclear.JE.Missing.zip)

**Comment by DZappala** [comment]
This may be solved by changing `common/journal_entries/CWP_WMD_JE.txt` on line 6 we reference `THIS` which may refer to the Journal Entry, rather than `ROOT` which refers to the country owning the JE.

**Comment by DZappala** [comment]
On line 56 we reference an empty `every_country = { }` block which may be invalidating this JE.

**Comment by DZappala** [comment]
Another likely cause for this issue may be the nation changing due to the Japan events. This JE should be set to `transferable = yes` and `can_revolution_be_inherited = yes`. It may also be prudent to remove the unnecessary "fail" state of this JE.
