### ISSUE TITLE
Currency cannot be Re/Devalued.

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#473]
After I redenominated twice from 100 to 1, I'm unable to re/devalue since around then. I'm not sure if its linked to redenom or just happened at the same time. Almost 10 years have passed since I'm locked out.
Same country and commit as prev report.

**Comment by PrimePhoenix9** [comment]
I'm attaching the oldest save I have, The following saves do no even have the flavor text "You have recently altered your currency" when you hover over the re/devalue buttons.
[Japan 1951 Currency Error.zip](https://github.com/Cold-War-Project/CWP-Main/files/12206934/Japan.1951.Currency.Error.zip)

**Comment by PrimePhoenix9** [comment]
I checked back and it doesn't seem to be related to redenomination at all. I'm unable to re/devalue any currency.
