### ISSUE TITLE
Drastic rise in Global GDP in IMF tab

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#474]
In 6 months, the Global GDP in the IMF tab has went from 5.74T to 61.5T. However it doesn't seem to affect any of the numbers inside the tab.

**Comment by PrimePhoenix9** [comment]
[japan_1962_12_28.zip](https://github.com/Cold-War-Project/CWP-Main/files/12206987/japan_1962_12_28.zip)
[japan_1963_06_26.zip](https://github.com/Cold-War-Project/CWP-Main/files/12206988/japan_1963_06_26.zip)

**Comment by PrimePhoenix9** [comment]
It seems to have resolved itself in a few months. However, around that time I have received 1000x higher IMF credits returns.
![2023_07_29_1](https://github.com/Cold-War-Project/CWP-Main/assets/46835664/512827fc-c7a3-42a2-9ef5-8bdad8f1558f)

**Comment by PrimePhoenix9** [comment]
The surge of IMF credit returns happened again. Attaching a save while this was happening.
[japan_1963_09_09.zip](https://github.com/Cold-War-Project/CWP-Main/files/12207040/japan_1963_09_09.zip)

**Comment by Arcadyi** [comment]
fixed in imf branch
