### ISSUE TITLE
countries which has devalued currency, paying tribute in their own currency but the overlord getting it without conversion ?

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#477]
no idea what exactly is happening , but i guess , countries which has devalued currency, paying tribute in their own currency but the overlord getting it without conversion ?  (example , so poland is paying 184 million PLN , and ussr getting 184 million SUR instead of likely 200k SUR after conversion or something )

**Comment by Marcogeorgez** [comment]
Example for the above ,
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/0ba2b307-14b4-495e-a98c-e1ff32ca9f65)
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/57eb7e89-46e4-46bf-b4b7-7e6b81f57d24)
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/7143651f-1347-49fd-aae0-5ede4e384130)
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/e81a622c-68f5-4f27-aaed-481a2cc5a91f)

this is on IMF branch
