### ISSUE TITLE
Deflation spiral trap for AI on IMF branch

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#478]
once a nation get into -10% deflation (AI) the nation cant ever get out of it , cause the entire economy crash (-100% throughput ) resulting in inflation (so it becomes -9% for example ) which results in the economy starting to work again (-50% throughput ), however while this happening over and over , the money supply will hit -100% , and every month the money supply will keep decreasing even on expansionary instead of increasing , which results in a deadlock situation.

**Comment by Marcogeorgez** [comment]
Screenshot :
1 July 1954
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/437ae2f9-4a6c-4b3b-a84c-155032edfc42)
4 August 1954
![image](https://github.com/Cold-War-Project/CWP-Main/assets/58277280/e8ed1f92-4364-491b-a045-776e01a4e9a0)
