### ISSUE TITLE
Expansionary money policy gives the malus of contractionary. Contractionary gives expansionary.

### ISSUE THREAD

**Issue by emelrad12** [Cold-War-Project/CWP-Main#546]
![image](https://github.com/Cold-War-Project/CWP-Main/assets/16389331/fb3ab3fb-7a57-444b-b191-f20e4d6ce949)
As you can see the expansionary is selected(by method of elimination as it is hidden)

**Comment by emelrad12** [comment]
![image](https://github.com/Cold-War-Project/CWP-Main/assets/16389331/b93ebf6a-ec88-4ca3-b6c7-40356f132c89)

**Comment by emelrad12** [comment]
![image](https://github.com/Cold-War-Project/CWP-Main/assets/16389331/61c3afb4-11fb-48e7-8168-711d0ffaada8)
Code

**Comment by AdrianKonca** [comment]
Already fixed in this [commit](https://github.com/Cold-War-Project/CWP-Main/commit/203c534536db373475167f98e25fbbeb02e1e6c2)
