### ISSUE TITLE
Fix pop investment

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#56]
Most of contribution efficiencies are useless due to this:
```
    state_farmers_investment_pool_contribution_add = 0.05
    state_shopkeepers_investment_pool_contribution_add = 0.05
    state_aristocrats_investment_pool_contribution_add = 0.1
    state_capitalists_investment_pool_contribution_add = 0.2
```

investment_pool_efficiency_mult currently can be used only for those 4 professions as only those can invest in stuff.

---
that’s an oversight. We should reduce the amt of money “conjured” from investments and then, at public choice theory, enable investing for all pop types.

---
So like 0.05 for rest of pops - if you have cooperative ownership, then it would be nicely buffed as heavy duty upper strata isn't here.
Even if 5% of building income accumulated endlessly in investment pool it wouldn't hurt pop SoL very much.

**Comment by JackEPepper** [comment]
added 5% contribution for all pops in micro foundations tech
