### ISSUE TITLE
How to create a new law?

### ISSUE THREAD

**Issue by ZRYZJ** [Cold-War-Project/CWP-Main#614]
I created a law in law_economic_system.txt  and  I can activate it by command , but I can't see it in the game.
Could anyone tell me how to solve the problem?

**Comment by raxo2222** [comment]
Those questions go to modding discord, or you can ask it in CWP discord

**Comment by ZRYZJ** [comment]
Sorry,but I am from China Mainland and I can't use discord because of the policy.(the government banned it)
Could you answer me in github ? please...

**Comment by raxo2222** [comment]
Since you can't use Discord from China you could use VPN, or post it there: https://steamcommunity.com/sharedfiles/filedetails/comments/2941771030
