### ISSUE TITLE
Goods Substitution GUI Error

### ISSUE THREAD

**Issue by JackEPepper** [Cold-War-Project/CWP-Main#633]
Error spam when goods substitution submenu is brought up in game`
![image](https://github.com/Cold-War-Project/CWP-Main/assets/100242026/0a6e4ab2-0271-4319-b3bb-53cf93930ffe)

**Comment by ghost** [comment]
It appears PDX forgot to mark some locs that were changed.
https://github.com/Cold-War-Project/CWP-Main/commit/faccbf322f431ba1bdbe61a04120c632d4296b12
