### ISSUE TITLE
Splines don't appear in game

### ISSUE THREAD

**Issue by Max200012** [Cold-War-Project/CWP-Main#639]
![image](https://github.com/user-attachments/assets/39480f8a-03d8-42e1-9e12-ea2036882e86)

![image](https://github.com/user-attachments/assets/4cbb3887-2413-4319-8c60-0087f5c0a797)

Possible cause of crash due to fuckery with army movements, I know it's a common correlation

**Comment by Max200012** [comment]
I'm personally out of ideas after battling with this for 2 days straight, I'll leave it to someone else to figure out

**Comment by hasan4938** [comment]
What exactly is the problem here?

**Comment by Max200012** [comment]
Fixed by @vasyl-pahut gj buddy
