### ISSUE TITLE
SoL seems to consistently drop globally as the game goes into the 60s.

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#67]
I played a game until 1966 as the DDR, and noticed I was having a lot of trouble maintaining my SoL. More problematic, however, was that Northern Europe and Italy were stuck in starvation conditions (<4 SoL). Belgium and the Soviet Union had gotten into cycles of constant revolts and civil war, with Belgium having 3 in the 6 years from 1960 to 1966.

Digging around in pop needs, I suspect its that food production for industrialized countries isn't able to keep up with population growth, an effect that disproportionately effects countries in the sweet spot between a medially-sized economy and medially-sized population (Sweden, Netherlands, Belgium), but especially impacted Europe.

The US did also see a notable drop in SoL in the 60s but its economy was big enough it seemed able to sustain itself. Smaller pop industrialized countries like Canada and Australia also faired pretty well.

**Comment by JackEPepper** [comment]
Going to keep an eye on this, I suspect its related to the immortality bug causing unsustainable growth.

**Comment by JackEPepper** [comment]
This was probably related to nations unlocking centralized banking and using the publicly traded PM without adequate financial services.  Calling it closed for now.
