### ISSUE TITLE
When this technology spreads to my nation, the game crashes the next day

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#68]
When this technology spreads to my nation, the game crashes (could be something else, but i have no idea what)

**Comment by EdnaldoPereira520** [comment]
[exception.txt](https://github.com/Cold-War-Project/CWP-Main/files/11128334/exception.txt)
[debug.log](https://github.com/Cold-War-Project/CWP-Main/files/11128335/debug.log)
[error.log](https://github.com/Cold-War-Project/CWP-Main/files/11128336/error.log)
[game.log](https://github.com/Cold-War-Project/CWP-Main/files/11128337/game.log)
idk wich one is useful, good luck team!
