### ISSUE TITLE
PMs that use semiconductors appear before the ability to create semiconductors

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#69]
This disconnect results in a dead zone where you have entirely useless PMs you can't touch
it shows itself most clearly with the Electronics manufactory, where both the bipolar transistor and integrated circuit PMs need semiconductors, making the bipolar transistor PM entirely redundant and skippable

**Comment by luigil101** [comment]
![aed60fbdc0964f8e3c5cb29e6abea684](https://user-images.githubusercontent.com/35119359/229271728-126f4e36-3043-4f45-bee6-1d878e51973f.png)
Didn't embed like I hoped
