### ISSUE TITLE
Throughput bonuses from the PMs that boost it are uncapped and stack with each other

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#70]
https://gyazo.com/aed60fbdc0964f8e3c5cb29e6abea684
Railroads
Bottom Text

**Comment by luigil101** [comment]
![aed60fbdc0964f8e3c5cb29e6abea684](https://user-images.githubusercontent.com/35119359/229271774-fb8e34db-b710-49c8-a374-5631a8cbc569.png)

**Comment by luigil101** [comment]
![50170d9b9369bd05dcd993aa5bc93756](https://user-images.githubusercontent.com/35119359/229272169-fa0f7c15-0092-4051-909b-92a3dae12624.png)
an update
if you have publicly traded and highways on at the same time, they infinitely magnify upon eachother, sending everything higher and higher
god help you if you forgot to put these magic beans on your resource producers

**Comment by luigil101** [comment]
Narrowed it down further
the spiral to infinity happens when the railroad hits level 45, and increases exponentially from there

**Comment by JackEPepper** [comment]
railways no longer give themselves throughput bonuses
