### ISSUE TITLE
C0000005 (EXCEPTION_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by DZappala** [Cold-War-Project/CWP-Main#93]
getting this annoying Unhandled Exception C0000005 (EXCEPTION_ACCESS_VIOLATION) CTD, its not related to a country, happened both for Italy and Canada.

**Comment by Haidenthal** [comment]
[exception.txt](https://github.com/Cold-War-Project/CWP-Main/files/11130091/exception.txt)
[debug.log](https://github.com/Cold-War-Project/CWP-Main/files/11130092/debug.log)
[error.log](https://github.com/Cold-War-Project/CWP-Main/files/11130093/error.log)
[game.log](https://github.com/Cold-War-Project/CWP-Main/files/11130094/game.log)
[system.log](https://github.com/Cold-War-Project/CWP-Main/files/11130095/system.log)
